# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='Notes'),
        ),
    ]
