# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20171230_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='registered_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
