# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20171229_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='registered_datetime',
            field=models.DateTimeField(default=b'2017-12-30'),
        ),
    ]
