# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20171213_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='Type Description...'),
        ),
    ]
